# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Enaco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Enaco
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'EnacoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnacoUITests' do
    # Pods for testing
  end

end
